"""empty message

Revision ID: 1feb499d9838
Revises: None
Create Date: 2016-02-14 21:27:57.445513

"""

# revision identifiers, used by Alembic.
revision = '1feb499d9838'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_type', sa.Column('game_wins_required', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_type', 'game_wins_required')
    ### end Alembic commands ###
